/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `person`;

CREATE TABLE `person` (
  `email` VARCHAR(255) NOT NULL PRIMARY KEY,
  `name` TEXT NOT NULL,
  `age` SMALLINT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

